CREATE DATABASE MARKET;

USE MARKET;

CREATE TABLE AREA(
TIPO INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL
);

-- MOSTRAR AREAS
CREATE PROC SPMOSTRAR_AREA
AS
SELECT * FROM AREA
GO

-- INSERTAR AREA
CREATE PROC SPINSERTAR_AREA
@TIPO INT,
@NOMBRE VARCHAR(30)
AS
INSERT INTO AREA VALUES (@TIPO,@NOMBRE)
GO

EXEC SPINSERTAR_AREA 2, 'as'

-- MODIFICAR AREA
CREATE PROC SPEDITAR_AREA
@TIPO INT,
@NOMBRE VARCHAR(30)
AS
UPDATE AREA SET
TIPO = @TIPO,
NOMBRE = @NOMBRE
WHERE TIPO = @TIPO
GO

DROP PROCEDURE SPEDITAR_AREA

-- ELIMINAR AREA
CREATE PROC SPELIMINAR_AREA
@TIPO INT
AS
DELETE FROM AREA WHERE TIPO = @TIPO
GO