USE MARKET;

CREATE TABLE FAMILIA(
TIPO INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL,
);

-- MOSTRAR
CREATE PROC SPMOSTRAR_FAMILIA
AS
SELECT * FROM FAMILIA
GO

-- INSERTAR
CREATE PROC SPINSERTAR_FAMILIA
@TIPO INT,
@NOMBRE VARCHAR(30)
AS
INSERT INTO FAMILIA VALUES (@TIPO,@NOMBRE)
GO

-- MODIFICAR 
CREATE PROC SPEDITAR_FAMILIA
@TIPO INT,
@NOMBRE VARCHAR(30)
AS
UPDATE FAMILIA
SET NOMBRE = @NOMBRE
WHERE TIPO = @TIPO
GO

-- ELIMINAR
CREATE PROC SPELIMINAR_FAMILIA
@TIPO INT
AS
DELETE FROM FAMILIA WHERE TIPO = @TIPO
GO