USE MARKET;

CREATE TABLE PRODUCTO(
CODIGO VARCHAR(20) NOT NULL PRIMARY KEY,
AREA INT,
FAMILIA INT,
MARCA VARCHAR(30),
DESCRIPCION VARCHAR(100),
PRESENTACION VARCHAR(50),
TAMAÑO INT,
CANTIDAD INT,
P_COMPRA DECIMAL (5,2),
P_VENTA DECIMAL(5,2)
CONSTRAINT FK_AREA FOREIGN KEY (AREA) REFERENCES AREA(TIPO),
CONSTRAINT FK_FAMILIA FOREIGN KEY (FAMILIA) REFERENCES FAMILIA(TIPO),
CONSTRAINT FK_TAMAÑO FOREIGN KEY (TAMAÑO) REFERENCES TAMAÑO(CODIGO)
);

DROP TABLE PRODUCTO

-- MOSTRAR PRODUCTOS
CREATE PROC SPMOSTRAR_PRODUCTO
AS
SELECT * FROM PRODUCTO
GO

INSERT INTO PRODUCTO VALUES ('C1C',1,1,'Cocinero','Regular','BOTELLA','1 Lt.',5,6.10,6.10)

EXEC SPMOSTRAR_PRODUCTO

-- MOSTRAR PRODUCTO DETALLADO
CREATE PROC SPMOSTRAR_PRODUCTO_DETALLADO
AS
SELECT P.CODIGO, A.NOMBRE AS AREA, F.NOMBRE AS FAMILIA, P.MARCA, P.DESCRIPCION, P.PRESENTACION, T.MEDIDA AS TAMAÑO, P.CANTIDAD, P.P_COMPRA, P.P_VENTA
FROM PRODUCTO P
INNER JOIN AREA A ON A.TIPO = P.AREA
INNER JOIN FAMILIA F ON F.TIPO = P.FAMILIA
INNER JOIN TAMAÑO T ON T.CODIGO = P.TAMAÑO
GO

EXEC SPMOSTRAR_PRODUCTO_DETALLADO

-- INSERTAR PRODUCTO
CREATE PROC SPINSERTAR_PRODUCTO
@CODIGO VARCHAR(20),
@AREA INT,
@FAMILIA INT,
@MARCA VARCHAR(30),
@DESCRIPCION VARCHAR(100),
@PRESENTACION VARCHAR(50),
@TAMAÑO VARCHAR(20),
@CANTIDAD INT,
@P_COMPRA DECIMAL (5,2),
@P_VENTA DECIMAL(5,2)
AS
INSERT INTO PRODUCTO VALUES(@CODIGO,@AREA,@FAMILIA,@MARCA,@DESCRIPCION,@PRESENTACION,@TAMAÑO,@CANTIDAD,@P_COMPRA,@P_VENTA)
GO

EXEC SPINSERTAR_PRODUCTO 'C2C',1,2,'Catalan','Regular','BOLSA','1 Kg.',60,2.80,3.20

-- EDITAR PRODUCTO
CREATE PROC SPEDITAR_PRODUCTO
@CODIGO VARCHAR(20),
@AREA INT,
@FAMILIA INT,
@MARCA VARCHAR(30),
@DESCRIPCION VARCHAR(100),
@PRESENTACION VARCHAR(50),
@TAMAÑO VARCHAR(20),
@CANTIDAD INT,
@P_COMPRA DECIMAL (5,2),
@P_VENTA DECIMAL(5,2)
AS
UPDATE PRODUCTO SET
AREA = @AREA,
FAMILIA = @FAMILIA,
MARCA = @MARCA,
DESCRIPCION = @DESCRIPCION,
PRESENTACION = @PRESENTACION,
TAMAÑO = @TAMAÑO,
CANTIDAD = @CANTIDAD,
P_COMPRA = @P_COMPRA,
P_VENTA = @P_VENTA
WHERE CODIGO = @CODIGO
GO

-- ELIMINAR PRODUCTO
CREATE PROC SPELIMINAR_PRODUCTO
@CODIGO VARCHAR(20)
AS
DELETE FROM PRODUCTO WHERE CODIGO = @CODIGO
GO

-- BUSCAR PRODUCTO
CREATE PROC SPBUSCAR_PRODUCTO
@MARCA VARCHAR(30)
AS
SELECT * FROM PRODUCTO
WHERE MARCA LIKE @MARCA + '%'
GO

EXEC SPBUSCAR_PRODUCTO 'oreo'