USE MARKET;

CREATE TABLE TAMAÑO(
CODIGO INT PRIMARY KEY,
MEDIDA VARCHAR(10)
);

-- MOSTRAR TAMAÑOS
CREATE PROC SPMOSTRAR_TAMAÑO
AS
SELECT * FROM TAMAÑO
GO

EXEC SPMOSTRAR_TAMAÑO

-- INSERTAR TAMAÑOS
CREATE PROC SPINSERTAR_TAMAÑO
@CODIGO INT,
@MEDIDA VARCHAR(10)
AS
INSERT INTO TAMAÑO VALUES (@CODIGO, @MEDIDA)
GO

EXEC SPINSERTAR_TAMAÑO 1, '500 Ml.'

-- MODIFICAR TAMAÑOS
CREATE PROC SPEDITAR_TAMAÑO
@CODIGO INT,
@MEDIDA VARCHAR(10)
AS
UPDATE TAMAÑO SET
MEDIDA = @MEDIDA
WHERE CODIGO = @CODIGO
GO

EXEC SPEDITAR_TAMAÑO 1, '500 Ml.'

-- ELMINAR TAMAÑOS
CREATE PROC SPELIMINAR_TAMAÑO
@CODIGO INT
AS
DELETE FROM TAMAÑO WHERE CODIGO = @CODIGO
GO